extends:
  - airbnb-base
  - plugin:jest/recommended
  - prettier
  - plugin:prettier/recommended
plugins:
  - import
  - json
  - jest
parserOptions:
  ecmaVersion: 2018
env:
  node: true
  jest: true
rules:
  import/prefer-default-export: off
  import/no-default-export: off
  no-console: warn
